// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pstkdxtuzyhrpoipclmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdGtkeHR1enlocnBvaXBjbG12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTMwNzIsImV4cCI6MjA1NTg2OTA3Mn0.M7mxurzb4EqHop2F661c2XlCgrzLFQpMuTt6NckUWYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);